from app.ai.response_generator import (
    generate_response
)


def response_node(state):

    memory_context = (
        state.get(
            "memory_context",
            ""
        )
    )

    # Debug only
    if memory_context:

        print(
            "\n========== MEMORY USED =========="
        )

        print(memory_context)

        print(
            "=================================\n"
        )

    # Response already generated by
    # invoice/hr/review/analytics agent

    if state.get("response"):

        return state

    # Fallback LLM response

    prompt = f"""
Previous Related Memories:

{memory_context}

Current User Message:

{state["message"]}

Instructions:

- Use previous memories if relevant.
- Do not display raw memory data.
- Do not display internal ticket references unless useful.
- Give a natural customer-facing response.
"""

    state["response"] = (
        generate_response(
            prompt
        )
    )

    return state